//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squares.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SquaresEntities : DbContext
    {
        public SquaresEntities()
            : base("name=SquaresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Piece> Pieces { get; set; }
        public virtual DbSet<Set> Sets { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int PROC_ChangeAdmin(string username, string fullName, string email, string passw, Nullable<int> id)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwParameter = passw != null ?
                new ObjectParameter("passw", passw) :
                new ObjectParameter("passw", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_ChangeAdmin", usernameParameter, fullNameParameter, emailParameter, passwParameter, idParameter);
        }
    
        public virtual int PROC_ChangeSet(string name, string description, Nullable<int> sizeData, string combinationData, Nullable<int> id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var sizeDataParameter = sizeData.HasValue ?
                new ObjectParameter("sizeData", sizeData) :
                new ObjectParameter("sizeData", typeof(int));
    
            var combinationDataParameter = combinationData != null ?
                new ObjectParameter("combinationData", combinationData) :
                new ObjectParameter("combinationData", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_ChangeSet", nameParameter, descriptionParameter, sizeDataParameter, combinationDataParameter, idParameter);
        }
    
        public virtual int PROC_ChangeUser(string username, string fullName, string email, string passw, Nullable<int> id)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwParameter = passw != null ?
                new ObjectParameter("passw", passw) :
                new ObjectParameter("passw", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_ChangeUser", usernameParameter, fullNameParameter, emailParameter, passwParameter, idParameter);
        }
    
        public virtual int PROC_CreateAdmin(string username, string fullName, string email, string passw)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwParameter = passw != null ?
                new ObjectParameter("passw", passw) :
                new ObjectParameter("passw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CreateAdmin", usernameParameter, fullNameParameter, emailParameter, passwParameter);
        }
    
        public virtual int PROC_CreatePiece(Nullable<int> setId, string thumb, string full)
        {
            var setIdParameter = setId.HasValue ?
                new ObjectParameter("setId", setId) :
                new ObjectParameter("setId", typeof(int));
    
            var thumbParameter = thumb != null ?
                new ObjectParameter("thumb", thumb) :
                new ObjectParameter("thumb", typeof(string));
    
            var fullParameter = full != null ?
                new ObjectParameter("full", full) :
                new ObjectParameter("full", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CreatePiece", setIdParameter, thumbParameter, fullParameter);
        }
    
        public virtual int PROC_CreateSet(string name, string description, Nullable<int> userid, Nullable<int> sizeData, string combinationData)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var sizeDataParameter = sizeData.HasValue ?
                new ObjectParameter("sizeData", sizeData) :
                new ObjectParameter("sizeData", typeof(int));
    
            var combinationDataParameter = combinationData != null ?
                new ObjectParameter("combinationData", combinationData) :
                new ObjectParameter("combinationData", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CreateSet", nameParameter, descriptionParameter, useridParameter, sizeDataParameter, combinationDataParameter);
        }
    
        public virtual int PROC_CreateUser(string username, string fullName, string email, string passw)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwParameter = passw != null ?
                new ObjectParameter("passw", passw) :
                new ObjectParameter("passw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CreateUser", usernameParameter, fullNameParameter, emailParameter, passwParameter);
        }
    
        public virtual int PROC_DeleteAdmin(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DeleteAdmin", idParameter);
        }
    
        public virtual int PROC_DeleteSet(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DeleteSet", idParameter);
        }
    
        public virtual int PROC_DeleteUser(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DeleteUser", idParameter);
        }
    }
}
